type WordPair = {
  de: string;
  tr: string;
};

const wordPairs: WordPair[] = [
  { de: "Änderung", tr: "Değişim" },
  { de: "Kugel", tr: "Küre" },
  { de: "Zahl", tr: "Sayı" },
  { de: "seltsam", tr: "Garip" },
  { de: "Faust", tr: "Yumruk" },
  { de: "Wurst", tr: "Sosis" },
  { de: "Nacht", tr: "Gece" },
  { de: "gehen", tr: "Gitmek" },
  { de: "Angebot", tr: "Teklif" },
  { de: "Mitglied", tr: "Üye" },
  { de: "bleiben", tr: "Kalmak" },
  { de: "Preis", tr: "Fiyat" },
  { de: "Reiter", tr: "Binici" },
  { de: "steil", tr: "Dik" },
  { de: "Gründung", tr: "Kuruluş" },
  { de: "Anfang", tr: "Başlangıç" },
  { de: "Ofen", tr: "Fırın" },
  { de: "Hahn", tr: "Horoz" },
  { de: "bitte", tr: "Rica" },
  { de: "Maus", tr: "Fare" },
  { de: "Schiff", tr: "Gemi" },
  { de: "Lupe", tr: "Büyüteç" },
  { de: "Stimmung", tr: "Atmosfer" },
  { de: "Glaube", tr: "İnanç" },
  { de: "betrachten", tr: "İncelemek" },
  { de: "schieben", tr: "İtmek" },
  { de: "Nebel", tr: "Sis" },
  { de: "Rakete", tr: "Roket" },
  { de: "beteiligen", tr: "Katmak" },
  { de: "lernen", tr: "Öğrenmek" },
  { de: "anbieten", tr: "Sunmak" },
  { de: "Glas", tr: "Cam" },
  { de: "sagen", tr: "Söylemek" },
  { de: "Rahmen", tr: "Çerçeve" },
  { de: "Besuch", tr: "Ziyaret" },
  { de: "Faden", tr: "İplik" },
  { de: "Bereich", tr: "Alan" },
  { de: "Prozent", tr: "Yüzde" },
  { de: "erzeugen", tr: "Yaratmak" },
  { de: "Ente", tr: "Ördek" },
  { de: "Daumen", tr: "Başparmak" },
  { de: "Schrank", tr: "Dolap" },
  { de: "Messer", tr: "Bıçak" },
  { de: "Loch", tr: "Delik" },
  { de: "Rock", tr: "Etek" },
  { de: "Bericht", tr: "Rapor" },
  { de: "Balance", tr: "Denge" },
  { de: "behandeln", tr: "Davranmak" },
  { de: "bewahren", tr: "Korumak" },
  { de: "Zelle", tr: "Hücre" },
  { de: "Nachricht", tr: "Haber" },
  { de: "entfernen", tr: "Uzaklaştırmak" },
  { de: "überzeugen", tr: "İnandırmak" },
  { de: "Bach", tr: "Dere" },
  { de: "Ausmaß", tr: "Ölçü" },
  { de: "still", tr: "Sakin" },
  { de: "Ordner", tr: "Dosya" },
  { de: "nutzen", tr: "Yararlanmak" },
  { de: "Apfel", tr: "Elma" },
  { de: "stumm", tr: "Dilsiz" },
  { de: "Urteil", tr: "Yargı" },
  { de: "Bauer", tr: "Çiftçi" },
  { de: "Arbeit", tr: "İş" },
  { de: "Gedicht", tr: "Şiir" },
  { de: "Tiefe", tr: "Derinlik" },
  { de: "enthalten", tr: "İçermek" },
  { de: "ziehen", tr: "Çekmek" },
  { de: "Abstand", tr: "Mesafe" },
  { de: "herstellen", tr: "Üretmek" },
  { de: "Zahlung", tr: "Ödeme" },
  { de: "Nachbar", tr: "Komşu" },
  { de: "Teller", tr: "Tabak" },
  { de: "Teilnahme", tr: "Katılım" },
  { de: "Gras", tr: "Çimen" },
  { de: "Nagel", tr: "Çivi" },
  { de: "schweben", tr: "Süzülmek" },
  { de: "Hose", tr: "Pantolon" },
  { de: "Pfarrer", tr: "Papaz" },
  { de: "werfen", tr: "Atmak" },
  { de: "Werk", tr: "Eser" },
  { de: "Dienst", tr: "Görev" },
  { de: "Taube", tr: "Güvercin" },
  { de: "Menschheit", tr: "İnsanlık" },
  { de: "Klingel", tr: "Zil" },
  { de: "grinsen", tr: "Sırıtmak" },
  { de: "Dauer", tr: "Süre" },
  { de: "Grundstück", tr: "Arsa" },
  { de: "Alter", tr: "Yaş" },
  { de: "Entwurf", tr: "Taslak" },
  { de: "umsonst", tr: "Bedava" },
  { de: "Bogen", tr: "Eğri" },
  { de: "Kirche", tr: "Kilise" },
  { de: "Stuhl", tr: "Sandalye" },
  { de: "Gegenteil", tr: "Karşıt" },
  { de: "Name", tr: "İsim" },
  { de: "mittel", tr: "Orta" },
  { de: "Wort", tr: "Kelime" },
  { de: "Flughafen", tr: "Havalimanı" },
  { de: "bieten", tr: "Sunmak" },
  { de: "Vorfall", tr: "Olay" },
  { de: "zustimmen", tr: "Onaylamak" },
  { de: "Junge", tr: "Oğlan" },
  { de: "Stolz", tr: "Gurur" },
  { de: "öffnen", tr: "Açmak" },
  { de: "Jungfrau", tr: "Bakire" },
  { de: "Treppe", tr: "Merdiven" },
  { de: "Umfang", tr: "Çevre" },
  { de: "Betrag", tr: "Tutar" },
  { de: "Höhe", tr: "Yükseklik" },
  { de: "Bürste", tr: "Fırça" },
  { de: "Menge", tr: "Miktar" },
  { de: "Anteil", tr: "Pay" },
  { de: "Schwein", tr: "Domuz" },
  { de: "Zoll", tr: "Vergi" },
  { de: "heben", tr: "Kaldırmak" },
  { de: "verweigern", tr: "Reddetmek" },
  { de: "Spiegel", tr: "Ayna" },
  { de: "Gewicht", tr: "Ağırlık" },
  { de: "Nase", tr: "Burun" },
  { de: "machen", tr: "Yapmak" },
  { de: "Bedingung", tr: "Şart" },
  { de: "Beispiel", tr: "Örnek" },
  { de: "vermuten", tr: "Zannetmek" },
  { de: "Hafer", tr: "Yulaf" },
  { de: "wählen", tr: "Seçmek" },
  { de: "wecken", tr: "Uyandırmak" },
  { de: "Zeuge", tr: "Tanık" },
  { de: "Ding", tr: "Şey" },
  { de: "Hebel", tr: "Kaldıraç" },
  { de: "Ton", tr: "Ses" },
  { de: "ermitteln", tr: "Belirlemek" },
  { de: "bestätigen", tr: "Doğrulamak" },
  { de: "Koffer", tr: "Bavul" },
  { de: "verstärken", tr: "Güçlendirmek" },
  { de: "Grenze", tr: "Sınır" },
  { de: "Beruf", tr: "Meslek" },
  { de: "Auskunft", tr: "Bilgi" },
  { de: "Staat", tr: "Devlet" },
  { de: "Aufsatz", tr: "Kompozisyon" },
  { de: "Antwort", tr: "Cevap" },
  { de: "Frage", tr: "Soru" },
  { de: "Impfung", tr: "Aşı" },
  { de: "Glocke", tr: "Çan" },
  { de: "Mauer", tr: "Duvar" },
  { de: "Staub", tr: "Toz" },
  { de: "Ergebnis", tr: "Sonuç" },
  { de: "feucht", tr: "Nemli" },
  { de: "Erbse", tr: "Bezelye" },
  { de: "Gebiet", tr: "Bölge" },
  { de: "Stunde", tr: "Saat" },
  { de: "Werbung", tr: "Reklam" },
  { de: "Butter", tr: "Tereyağı" },
  { de: "Flugzeug", tr: "Uçak" },
  { de: "Fahrer", tr: "Sürücü" },
  { de: "Firma", tr: "Şirket" },
  { de: "Weg", tr: "Yol" },
  { de: "Absender", tr: "Gönderen" },
  { de: "wenig", tr: "Az" },
  { de: "Turm", tr: "Kule" },
  { de: "Zeitung", tr: "Gazete" },
  { de: "Titel", tr: "Başlık" },
  { de: "Huhn", tr: "Tavuk" },
  { de: "Markt", tr: "Pazar" },
  { de: "Strumpf", tr: "Topuk" },
  { de: "Kupfer", tr: "Bakır" },
  { de: "Aufgabe", tr: "Görev" },
  { de: "Nachfolger", tr: "Halef" },
  { de: "Zunge", tr: "Dil" },
  { de: "beenden", tr: "Bitirmek" },
  { de: "Straße", tr: "Cadde" },
  { de: "Auswahl", tr: "Seçenek" },
  { de: "Geruch", tr: "Koku" },
  { de: "ausgeben", tr: "Harcamak" },
  { de: "Steigerung", tr: "Artış" },
  { de: "Verkehr", tr: "Trafik" },
  { de: "Laufbahn", tr: "Yörünge" },
  { de: "Verdacht", tr: "Şüphe" },
  { de: "laut", tr: "Gürültülü" },
  { de: "schütteln", tr: "Sallamak" },
  { de: "Teppich", tr: "Halı" },
  { de: "Hemd", tr: "Gömlek" },
  { de: "Kunde", tr: "Müşteri" },
];

// Die ersten 80 Paare als Lernwörter, die nächsten als neue Wörter im Recognition-Test,
// die letzten 8 Paare als separate Übungswörter (kommen im Hauptexperiment nicht vor).
const practicePairs = wordPairs.slice(wordPairs.length - 8);
const studyPairs = wordPairs.slice(0, 80);
const newPairs = wordPairs.slice(80, wordPairs.length - 8);

export const stimuli = {
  de: {
    study: studyPairs.map((pair) => pair.de),
    new: newPairs.map((pair) => pair.de),
  },
  tr: {
    study: studyPairs.map((pair) => pair.tr),
    new: newPairs.map((pair) => pair.tr),
  },
};

export const practiceStimuli = {
  de: practicePairs.map((pair) => pair.de),
  tr: practicePairs.map((pair) => pair.tr),
};
